set -g set-clipboard on
set -g mouse on
set -g base-index 1
set -g default-terminal "tmux-256color"
set -g history-limit 10000
set-option -g allow-rename off

if-shell 'tmux -V | grep -q "3.[4-9]"' 'set -g codepoint-widths "U+2632=1"'
set-option -ga terminal-features ",tmux-256color:RGB"

set -sg escape-time 0
set -g bell-action any
setw -g monitor-activity on
set -g visual-activity off

unbind C-b
set-option -g prefix `
bind-key ` send-prefix

bind -T root F12 \
    set prefix None \;\
    set key-table off \;\
    set status-style "bg=colour32" \;\
    refresh-client -S

bind -T off F12 \
    set -u prefix \;\
    set -u key-table \;\
    set -u status-style \;\
    refresh-client -S

unbind %
unbind '"'
bind '\' split-window -h
bind '-' split-window -v
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

bind -n M-[  previous-window
bind -n M-] next-window

bind C-n setw synchronize-panes

bind r source-file ~/.tmux.conf
set -g status-left-length 30
set -g status-interval 1

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'wfxr/tmux-power'
set -g @tmux_power_theme 'coral'
run '/usr/share/tmux-plugin-manager/tpm'
