set -g set-clipboard on
set -g mouse on
set -g base-index 1
set-option -g allow-rename off
set -g default-terminal "tmux-256color"
set -g history-limit 10000

if-shell 'tmux -V | grep -q "3.[4-9]"' 'set -g codepoint-widths "U+2632=1"'
set-option -ga terminal-features ",tmux-256color:RGB"

# No delay for escape key press
set -sg escape-time 0

# Activity
set -g bell-action any
setw -g monitor-activity off
set -g visual-activity off


# Change prefix key to backtick (`)
unbind C-b
set-option -g prefix `

    #set status-style "bg=gray" \;
bind -T root F12 \
    set prefix None \;\
    set key-table off \;\
    set status-style "bg=colour32" \;\
    refresh-client -S

bind -T off F12 \
    set -u prefix \;\
    set -u key-table \;\
    set -u status-style \;\
    refresh-client -S

# So we can still use ` when needed
#bind-key C-a set-option -g prefix C-a
#bind-key C-b set-option -g prefix `

# Easy bindings for split
unbind %
unbind '"'


bind '\' split-window -h
bind '-' split-window -v
#bind -n M-Left select-pane -L
#bind -n M-Right select-pane -R
#bind -n M-Up select-pane -U
#jbind -n M-Down select-pane -D
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

#bind-key -n KP0 select-window -t :0
#bind-key -n KP1 select-window -t :1
#bind-key -n KP2 select-window -t :2
#bind-key -n KP3 select-window -t :3
#bind-key -n KP4 select-window -t :4
#bind-key -n KP5 select-window -t :5
#bind-key -n KP6 select-window -t :6
#bind-key -n KP7 select-window -t :7
#bind-key -n KP8 select-window -t :8
#bind-key -n KP9 select-window -t :9

set -sg escape-time 0

#bind -n S-Left  previous-window
#bind -n S-Right next-window
bind -n M-[  previous-window
bind -n M-] next-window

bind C-n setw synchronize-panes

# Reload tmux config
bind r source-file ~/.tmux.conf

set -g status-left-length 30
set -g status-interval 1

# manager
set -g @plugin 'tmux-plugins/tpm'

# jimeh themes
#set -g @plugin 'jimeh/tmux-themepack'
#set -g @themepack 'powerline/block/orange'

# wfxr themes
set -g @plugin 'wfxr/tmux-power'
set -g @tmux_power_theme 'coral'
# run plugin
run '/usr/share/tmux-plugin-manager/tpm'

