CompileFlags:
  Add: [
    -std=c++20,
    -Wall,
    -Wextra,
    -Wpedantic,
    -Wshadow,
    -Wconversion,
    -Wsign-conversion,
    -Wnull-dereference,
    -Wcast-align,
    -Wunused,
    -Wdouble-promotion,
    -Wduplicated-cond,
    -Wduplicated-branches,
    -Wlogical-op,
    -Wuseless-cast,
    -Wrestrict,
    -Wold-style-cast,
    -Wformat=2,
    -Weverything,
    -Wno-c++98-compat,
    -Wno-c++20-extensions,
  ]
Diagnostics:
  UnusedIncludes: Strict
  MissingIncludes: Strict
  Includes:
    AnalyzeAngledIncludes: false
  ClangTidy:
    Add: [bugprone-*, performance-*, readability-*, modernize-*, cppcoreguidelines-*, misc-*]
    Remove: [
      modernize-use-trailing-return-type,
      cppcoreguidelines-pro-type-reinterpret-cast,
      cppcoreguidelines-pro-type-vararg,
      cppcoreguidelines-avoid-const-or-ref-data-members,
      readability-uppercase-literal-suffix,
      readability-braces-around-statements,
      readability-identifier-length,
      misc-non-private-member-variables-in-classes
    ]
    CheckOptions:
      readability-identifier-naming.VariableCase: lower_case
      readability-identifier-naming.FunctionCase: lower_case
      readability-identifier-naming.ClassCase: CamelCase
      readability-function-cognitive-complexity.Threshold: '50'
      readability-identifier-naming.ClassIgnoredRegexp: '.*(_t$|_type).*'
      readability-identifier-naming.StructIgnoredRegexp: '.*(_t$|_type).*'
      readability-magic-numbers.IgnoredIntegerValues: '0;1;2;3;4;0xFFFF'

InlayHints:
  TypeNameLimit: 32
